config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes, only: %i[index show]
  root 'recipes#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    response = Contentful::RecipeService.call(:recipes_list)
    @recipes = response[:data]
    respond_to do |format|
      format.html
      format.json { render json: @recipes, status: response[:status] }
    end
  end

  def show
    response = Contentful::RecipeService.call(:recipe_details, params[:id])
    @recipe = response[:data]
    respond_to do |format|
      format.html
      format.json { render json: @recipe, status: response[:status] }
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
  def recipe_image(recipe)
    recipe[:image].present? ? recipe[:image] : 'no-image.png'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class='row'>
  <% @recipes.each do |recipe| %>
    <div class='col-sm-3'>
      <div class='card'>
        <%= image_tag recipe_image(recipe), class: 'card-img-top' %>
        <div class='card-body'>
          <h5 class='card-title text-center'>
            <%= link_to recipe[:title], recipe_path(recipe[:id]), class: 'recipe-link' %>
          </h5>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<% if @recipe.present? %>
  <div class='row'>
    <div class='col-sm-12 p-1'>
      <div class='card text-center mt-3'>
        <div class='card-header'>
          <%= @recipe[:title] %>
        </div>
        <%= image_tag recipe_image(@recipe) %>
        <div class='card-body'>
          <h5 class='card-title'>
            <%= @recipe[:chef_name] %>
          </h5>
          <p class='card-text'>
            <%= @recipe[:description] %>
          </p>
          <div class='btn-toolbar'>
            <% @recipe[:tags_list].each do |tag| %>
              <%= button_tag tag, disabled: true , class: 'btn btn-secondary' %>
            <% end if @recipe[:tags_list].present? %>
          </div>
        </div>
      </div>
      <%= link_to 'All Recipes', recipes_path  %>
    </div>
  </div>
<% else %>
  <div class="alert alert-danger" role="alert">
    No such recipe Found
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class='navbar navbar-dark mb-3'>
  <%= link_to 'All Recipes', root_url %>
</nav>